// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ItemLite {
    #[prost(int64, tag = "1")]
    pub uuid: i64,
    #[prost(int32, tag = "2")]
    pub config_id: i32,
    #[prost(int64, tag = "3")]
    pub count: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExchangePriceItemData {
    #[prost(int32, tag = "1")]
    pub price: i32,
    #[prost(int32, tag = "2")]
    pub num: i32,
    #[prost(message, optional, tag = "3")]
    pub item_info: ::core::option::Option<ItemLite>,
    #[prost(string, tag = "4")]
    pub guid: ::prost::alloc::string::String,
    #[prost(int64, tag = "5")]
    pub notice_time: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExchangeNoticeDetailReply {
    #[prost(message, repeated, tag = "2")]
    pub items: ::prost::alloc::vec::Vec<ExchangePriceItemData>,
    #[prost(int32, tag = "3")]
    pub total_page: i32,
    #[prost(int32, tag = "4")]
    pub cur_page: i32,
    #[prost(int64, tag = "5")]
    pub min_price: i64,
    #[prost(enumeration = "EErrorCode", tag = "6")]
    pub err_code: i32,
}
/// Wire-compatible with `serv_world.World.ExchangeNoticeDetail_Ret`.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExchangeNoticeDetailRet {
    #[prost(message, optional, tag = "1")]
    pub ret: ::core::option::Option<ExchangeNoticeDetailReply>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EErrorCode {
    ErrSuccess = 0,
    ErrNoRecord = 101,
}
impl EErrorCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::ErrSuccess => "ERR_SUCCESS",
            Self::ErrNoRecord => "ERR_NO_RECORD",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ERR_SUCCESS" => Some(Self::ErrSuccess),
            "ERR_NO_RECORD" => Some(Self::ErrNoRecord),
            _ => None,
        }
    }
}
